[pytest]
norecursedirs = archives .git .pytest_cache __pycache__ build dist
filterwarnings =
    ignore::DeprecationWarning:binance\.ws\.websocket_api
    ignore::DeprecationWarning:websockets\.legacy
    ignore:There is no current event loop:DeprecationWarning:binance\.helpers
